name: MinecraftParty
main: whirss.minecraftparty.Main
version: 1.7
author: Whirss, InstanceLabs
softdepend: [PlaceholderAPI, Vault]
commands:
   minecraftparty:
      aliases: [mp, mcparty, mcp]
      description: Command for players
      usage: /minecraftparty [action]
   minecraftpartyadmin:
      aliases: [mpadmin, mpa, mcpartyadmin]
      description: Command for admins
      usage: /minecraftpartyadmin [action]
